# @package _global_

defaults:
  - /model/transformer_large_potential

ranged_models:
  - _target_: ffdiffusion.models.RangedModel
    model: ${model.transformer_large_potential}
    range: [1.0, 0.0]
